#!/usr/bin/env python3
"""Rasterise digits 0-9 and ':' from a TTF into an antialiased grayscale C
header for the large clock font. Run from the project root:

    python3 tools/genfont.py > src/font_large.h
"""
from PIL import Image, ImageFont, ImageDraw

FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf"
SIZE = 16
DIGITS = "0123456789"

font = ImageFont.truetype(FONT_PATH, SIZE)

# Common vertical extent + monospace cell width across the digits.
dboxes = [font.getbbox(c) for c in DIGITS]
minT = min(b[1] for b in dboxes)
maxB = max(b[3] for b in dboxes)
H = maxB - minT
W = max(b[2] - b[0] for b in dboxes)


def render(ch, cell_w):
    img = Image.new("L", (cell_w, H), 0)
    draw = ImageDraw.Draw(img)
    l, t, r, b = font.getbbox(ch)
    x = (cell_w - (r - l)) // 2 - l      # centre ink horizontally
    draw.text((x, -minT), ch, fill=255, font=font)  # align to common baseline
    return img


def emit(name, img):
    w, h = img.size
    px = img.load()
    print(f"static const uint8_t {name}[{h}][{w}] = {{")
    for y in range(h):
        row = ",".join(f"{px[x, y]:3d}" for x in range(w))
        print(f"    {{{row}}},")
    print("};")


cb = font.getbbox(":")
colon_w = cb[2] - cb[0]

print("#ifndef FONT_LARGE_INCLUDED")
print("#define FONT_LARGE_INCLUDED")
print()
print("#include <stdint.h>")
print()
print("// Antialiased (grayscale 0-255) large digits + colon, generated by")
print("// tools/genfont.py from DejaVu Sans Condensed Bold. Each value is a")
print("// per-pixel brightness; the renderer scales the draw colour by it.")
print(f"#define FONT_LARGE_W {W}")
print(f"#define FONT_LARGE_H {H}")
print(f"#define FONT_LARGE_COLON_W {colon_w}")
print()
print(f"static const uint8_t FONT_LARGE_DIGITS[10][{H}][{W}] = {{")
for c in DIGITS:
    img = render(c, W)
    px = img.load()
    print("  {")
    for y in range(H):
        row = ",".join(f"{px[x, y]:3d}" for x in range(W))
        print(f"    {{{row}}},")
    print("  },")
print("};")
print()
emit("FONT_LARGE_COLON", render(":", colon_w))
print()
print("#endif // FONT_LARGE_INCLUDED")
